;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"RODATA"

L0004:
	.byte	$53,$74,$75,$64,$79,$54,$6F,$6E,$69,$67,$68,$74,$00
	.res	117,$00

.segment	"CODE"

	ldy     #$82
	jsr     subysp
	ldy     #$00
L0005:	lda     L0004,y
	sta     (sp),y
	iny
	cpy     #$82
	bne     L0005
	jsr     push0
	lda     #$30
	jsr     pusha
L0008:	ldy     #$02
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	ina
	bne     L000E
	inx
L000E:	ldy     #$01
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	clc
	adc     #$03
	bcc     L000F
	inx
	clc
L000F:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	lda     (sp)
	sta     (ptr1)
	ldy     #$02
	jsr     ldaxysp
	cmp     #$82
	txa
	sbc     #$00
	bcc     L0008
	ldx     #$00
	txa
	ldy     #$01
	jsr     staxysp
	lda     (sp)
	ina
	sta     (sp)
	bra     L0008

.endproc

